   struct node* root = new node(1);
   root-> left = new node(2);
   root->right = new node(3);
   root->left->left = new node(4);
   root->left->right = new node(5);
   root->right->left = new node(6);
   root->right->right = new node(7);
   pre_order(root);
   cout<<endl;
   in_order(root);
   cout<<endl;
   post_order(root);